name: Release Build

on:
  release:
    types: [published]

jobs:
  release:
    name: Release build

    strategy:
      matrix:
        os: ['ubuntu-latest']
        go-version: [1.18.x]

    runs-on: ${{ matrix.os }}

    steps:
      -
        name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      -
        name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          # Fetch whole repository to get release tags
          # See https://github.com/actions/checkout/issues/701
          fetch-depth: 0

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
